# Generated by Django 4.2.23 on 2025-08-12 21:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import pulp_rpm.app.models.package
import pulpcore.app.models.base
import pulpcore.app.util
import uuid


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# pulp_rpm.app.migrations.0003_DATA_incorrect_json
# pulp_rpm.app.migrations.0008_advisory_pkg_sumtype_as_int
# pulp_rpm.app.migrations.0015_repo_metadata
# pulp_rpm.app.migrations.0016_dist_tree_nofk
# pulp_rpm.app.migrations.0017_merge_advisory_collections
# pulp_rpm.app.migrations.0019_migrate_updatecollection_data
# pulp_rpm.app.migrations.0025_remove_orphaned_subrepos
# pulp_rpm.app.migrations.0027_checksum_null
# pulp_rpm.app.migrations.0029_rpmpublication_sqlite_metadata
# pulp_rpm.app.migrations.0030_DATA_fix_updaterecord
# pulp_rpm.app.migrations.0033_new_distribution_model
# pulp_rpm.app.migrations.0035_fix_auto_publish
# pulp_rpm.app.migrations.0037_DATA_remove_rpmrepository_sub_repo
# pulp_rpm.app.migrations.0039_disttree_digest
# pulp_rpm.app.migrations.0044_noartifact_modules
# pulp_rpm.app.migrations.0045_modulemd_fields
# pulp_rpm.app.migrations.0047_modulemd_datefield
# pulp_rpm.app.migrations.0048_artifacts_dependencies_fix
# pulp_rpm.app.migrations.0049_profiles_fix
# pulp_rpm.app.migrations.0057_rpmpublication_checksum_type_and_more
# pulp_rpm.app.migrations.0060_rpmpublication_compression_type_empty
# pulp_rpm.app.migrations.0061_fix_modulemd_defaults_digest

class Migration(migrations.Migration):

    replaces = [('rpm', '0001_initial'), ('rpm', '0002_updaterecord_reboot_suggested'), ('rpm', '0003_DATA_incorrect_json'), ('rpm', '0004_add_metadata_signing_service_fk'), ('rpm', '0005_optimize_sync'), ('rpm', '0006_opensuse_support'), ('rpm', '0007_checksum_types'), ('rpm', '0008_advisory_pkg_sumtype_as_int'), ('rpm', '0009_revision_null'), ('rpm', '0010_revision_null_redo'), ('rpm', '0011_rpmremote_sles_auth_token'), ('rpm', '0012_remove_pkg_group_env_cat_related_pkgs'), ('rpm', '0013_RAW_rpm_evr_extension'), ('rpm', '0014_rpmrepository_package_retention_policy'), ('rpm', '0015_repo_metadata'), ('rpm', '0016_dist_tree_nofk'), ('rpm', '0017_merge_advisory_collections'), ('rpm', '0018_updatecollection__update_record'), ('rpm', '0019_migrate_updatecollection_data'), ('rpm', '0020_remove_updatecollection_m2m'), ('rpm', '0021_rename_updatecollection_update_record'), ('rpm', '0022_add_collections_related_name'), ('rpm', '0023_increase_distribution_release_short'), ('rpm', '0024_change_subrepo_relation_properties'), ('rpm', '0025_remove_orphaned_subrepos'), ('rpm', '0026_add_gpgcheck_options'), ('rpm', '0027_checksum_null'), ('rpm', '0028_rpmrepository_last_sync_repomd_cheksum'), ('rpm', '0029_rpmpublication_sqlite_metadata'), ('rpm', '0030_DATA_fix_updaterecord'), ('rpm', '0031_modulemd_static_context'), ('rpm', '0032_ulnremote'), ('rpm', '0033_new_distribution_model'), ('rpm', '0034_auto_publish'), ('rpm', '0035_fix_auto_publish'), ('rpm', '0036_checksum_type'), ('rpm', '0037_DATA_remove_rpmrepository_sub_repo'), ('rpm', '0037_update_json_field'), ('rpm', '0038_fix_sync_optimization'), ('rpm', '0039_disttree_digest'), ('rpm', '0040_rpmalternatecontentsource'), ('rpm', '0041_modulemdobsolete'), ('rpm', '0042_alter_repometadatafile_data_type'), ('rpm', '0043_textfield_conversion'), ('rpm', '0044_noartifact_modules'), ('rpm', '0045_modulemd_fields'), ('rpm', '0046_rbac_perms'), ('rpm', '0047_modulemd_datefield'), ('rpm', '0048_artifacts_dependencies_fix'), ('rpm', '0049_profiles_fix'), ('rpm', '0050_alter_addon_pulp_id_alter_checksum_pulp_id_and_more'), ('rpm', '0051_alter_distributiontree_unique_together_and_more'), ('rpm', '0052_modulemd_digest'), ('rpm', '0053_rpmdistribution_generate_repo_config'), ('rpm', '0054_remove_gpg_fields'), ('rpm', '0055_add_repo_config_field'), ('rpm', '0056_remove_rpmpublication_sqlite_metadata_and_more'), ('rpm', '0057_rpmpublication_checksum_type_and_more'), ('rpm', '0058_alter_addon_repository_alter_variant_repository'), ('rpm', '0059_rpmpublication_compression_type_and_more'), ('rpm', '0060_rpmpublication_compression_type_empty'), ('rpm', '0061_fix_modulemd_defaults_digest'), ('rpm', '0062_rpmpackagesigningservice_and_more')]

    initial = True

    dependencies = [
        ('core', '0091_systemid'),
        ('core', '0106_alter_artifactdistribution_distribution_ptr_and_more'),
        ('core', '0114_remove_task_args_remove_task_kwargs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionTree',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_distributiontree', serialize=False, to='core.content')),
                ('header_version', models.CharField(max_length=10)),
                ('release_name', models.CharField(max_length=50)),
                ('release_short', models.CharField(max_length=20)),
                ('release_version', models.CharField(max_length=10)),
                ('release_is_layered', models.BooleanField(default=False)),
                ('base_product_name', models.CharField(max_length=50, null=True)),
                ('base_product_short', models.CharField(max_length=20, null=True)),
                ('base_product_version', models.CharField(max_length=10, null=True)),
                ('arch', models.CharField(max_length=30)),
                ('build_timestamp', models.FloatField()),
                ('instimage', models.CharField(max_length=50, null=True)),
                ('mainimage', models.CharField(max_length=50, null=True)),
                ('discnum', models.IntegerField(null=True)),
                ('totaldiscs', models.IntegerField(null=True)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('header_version', 'release_name', 'release_short', 'release_version', 'arch', 'build_timestamp')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='ModulemdDefaults',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_modulemddefaults', serialize=False, to='core.content')),
                ('module', models.CharField(max_length=255)),
                ('stream', models.CharField(max_length=255)),
                ('profiles', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('digest', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_package', serialize=False, to='core.content')),
                ('name', models.CharField(max_length=255)),
                ('epoch', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=255)),
                ('release', models.CharField(max_length=255)),
                ('arch', models.CharField(max_length=20)),
                ('pkgId', models.CharField(max_length=128, unique=True)),
                ('checksum_type', models.CharField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], max_length=10)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('changelogs', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('files', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('requires', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('provides', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('conflicts', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('obsoletes', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('suggests', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('enhances', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('recommends', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('supplements', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('location_base', models.TextField()),
                ('location_href', models.TextField()),
                ('rpm_buildhost', models.TextField()),
                ('rpm_group', models.TextField()),
                ('rpm_license', models.TextField()),
                ('rpm_packager', models.TextField()),
                ('rpm_sourcerpm', models.TextField()),
                ('rpm_vendor', models.TextField()),
                ('rpm_header_start', models.BigIntegerField(null=True)),
                ('rpm_header_end', models.BigIntegerField(null=True)),
                ('is_modular', models.BooleanField(default=False)),
                ('size_archive', models.BigIntegerField(null=True)),
                ('size_installed', models.BigIntegerField(null=True)),
                ('size_package', models.BigIntegerField(null=True)),
                ('time_build', models.BigIntegerField(null=True)),
                ('time_file', models.BigIntegerField(null=True)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('name', 'epoch', 'version', 'release', 'arch', 'checksum_type', 'pkgId')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='PackageLangpacks',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_packagelangpacks', serialize=False, to='core.content')),
                ('matches', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('digest', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='RpmPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_rpmpublication', serialize=False, to='core.publication')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.publication',),
        ),
        migrations.CreateModel(
            name='RpmRemote',
            fields=[
                ('remote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_rpmremote', serialize=False, to='core.remote')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.remote',),
        ),
        migrations.CreateModel(
            name='RpmRepository',
            fields=[
                ('repository_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_rpmrepository', serialize=False, to='core.repository')),
                ('sub_repo', models.BooleanField(default=False)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.repository',),
        ),
        migrations.CreateModel(
            name='UpdateCollection',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField()),
                ('shortname', models.TextField()),
                ('module', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateRecord',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_updaterecord', serialize=False, to='core.content')),
                ('id', models.CharField(db_index=True, max_length=255)),
                ('updated_date', models.TextField()),
                ('description', models.TextField()),
                ('issued_date', models.TextField()),
                ('fromstr', models.TextField()),
                ('status', models.TextField()),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('version', models.TextField()),
                ('type', models.TextField()),
                ('severity', models.TextField()),
                ('solution', models.TextField()),
                ('release', models.TextField()),
                ('rights', models.TextField()),
                ('pushcount', models.TextField(blank=True)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('reboot_suggested', models.BooleanField(default=False)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='UpdateReference',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('href', models.TextField()),
                ('ref_id', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('ref_type', models.TextField()),
                ('update_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='rpm.updaterecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateCollectionPackage',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('arch', models.TextField()),
                ('epoch', models.TextField()),
                ('filename', models.TextField()),
                ('name', models.TextField()),
                ('reboot_suggested', models.BooleanField(default=False)),
                ('release', models.TextField()),
                ('src', models.TextField()),
                ('sum', models.TextField()),
                ('sum_type', models.TextField()),
                ('version', models.TextField()),
                ('update_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='rpm.updatecollection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='updatecollection',
            name='update_record',
            field=models.ManyToManyField(related_name='collections', to='rpm.updaterecord'),
        ),
        migrations.CreateModel(
            name='RpmDistribution',
            fields=[
                ('basedistribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_rpmdistribution', serialize=False, to='core.basedistribution')),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rpm_rpmdistribution', to='core.publication')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.basedistribution',),
        ),
        migrations.CreateModel(
            name='RepoMetadataFile',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_repometadatafile', serialize=False, to='core.content')),
                ('data_type', models.CharField(max_length=20)),
                ('checksum_type', models.CharField(max_length=6)),
                ('checksum', models.CharField(max_length=128)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('data_type', 'checksum')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='PackageGroup',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_packagegroup', serialize=False, to='core.content')),
                ('id', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('user_visible', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('packages', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('biarch_only', models.BooleanField(default=False)),
                ('desc_by_lang', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name_by_lang', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('related_packages', models.ManyToManyField(related_name='rpm_packagegroup', to='rpm.package')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='PackageEnvironment',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_packageenvironment', serialize=False, to='core.content')),
                ('id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('display_order', models.IntegerField(null=True)),
                ('group_ids', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('option_ids', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('desc_by_lang', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name_by_lang', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('optionalgroups', models.ManyToManyField(related_name='optionalgroups_to_env', to='rpm.packagegroup')),
                ('packagegroups', models.ManyToManyField(related_name='packagegroups_to_env', to='rpm.packagegroup')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_packagecategory', serialize=False, to='core.content')),
                ('id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('display_order', models.IntegerField(null=True)),
                ('group_ids', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('desc_by_lang', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name_by_lang', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('packagegroups', models.ManyToManyField(related_name='rpm_packagecategory', to='rpm.packagegroup')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('variant_id', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('packages', models.CharField(max_length=50)),
                ('source_packages', models.CharField(max_length=50, null=True)),
                ('source_repository', models.CharField(max_length=50, null=True)),
                ('debug_packages', models.CharField(max_length=50, null=True)),
                ('debug_repository', models.CharField(max_length=50, null=True)),
                ('identity', models.CharField(max_length=50, null=True)),
                ('distribution_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='rpm.distributiontree')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.repository')),
            ],
            options={
                'unique_together': {('variant_id', 'uid', 'name', 'type', 'packages', 'distribution_tree')},
            },
        ),
        migrations.CreateModel(
            name='Modulemd',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_modulemd', serialize=False, to='core.content')),
                ('name', models.CharField(max_length=255)),
                ('stream', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('context', models.CharField(max_length=255)),
                ('arch', models.CharField(max_length=255)),
                ('dependencies', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('artifacts', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('packages', models.ManyToManyField(related_name='rpm_modulemd', to='rpm.package')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('name', 'stream', 'version', 'context', 'arch')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=128)),
                ('platforms', models.CharField(max_length=20)),
                ('distribution_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rpm.distributiontree')),
            ],
            options={
                'unique_together': {('name', 'path', 'platforms', 'distribution_tree')},
            },
        ),
        migrations.CreateModel(
            name='Checksum',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('path', models.CharField(max_length=128)),
                ('checksum', models.CharField(max_length=128, null=True)),
                ('distribution_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checksums', to='rpm.distributiontree')),
            ],
            options={
                'unique_together': {('path', 'checksum', 'distribution_tree')},
            },
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('addon_id', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('packages', models.CharField(max_length=50)),
                ('distribution_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='rpm.distributiontree')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addons', to='core.repository')),
            ],
            options={
                'unique_together': {('addon_id', 'uid', 'name', 'type', 'packages', 'distribution_tree')},
            },
        ),
        migrations.AlterField(
            model_name='updatecollection',
            name='module',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='metadata_signing_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rpm_rpmrepository', to='core.asciiarmoreddetachedsigningservice'),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='last_sync_remote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rpm_rpmrepository', to='core.remote'),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='last_sync_repo_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='last_sync_revision_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='updatecollectionpackage',
            name='relogin_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updatecollectionpackage',
            name='restart_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='updatecollection',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='updatecollection',
            name='shortname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rpmpublication',
            name='metadata_checksum_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], default='sha256', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rpmpublication',
            name='package_checksum_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], default='sha256', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='original_checksum_types',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='updatecollectionpackage',
            name='sum_type_temp',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='updatecollectionpackage',
            name='sum_type',
        ),
        migrations.RenameField(
            model_name='updatecollectionpackage',
            old_name='sum_type_temp',
            new_name='sum_type',
        ),
        migrations.AlterField(
            model_name='rpmrepository',
            name='last_sync_revision_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rpmrepository',
            name='last_sync_revision_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rpmremote',
            name='sles_auth_token',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.RemoveField(
            model_name='packagecategory',
            name='packagegroups',
        ),
        migrations.RemoveField(
            model_name='packageenvironment',
            name='optionalgroups',
        ),
        migrations.RemoveField(
            model_name='packageenvironment',
            name='packagegroups',
        ),
        migrations.RemoveField(
            model_name='packagegroup',
            name='related_packages',
        ),
        migrations.RunSQL(
            sql="\ncreate type pulp_evr_array_item as (\n  n       NUMERIC,\n  s       TEXT\n);\n\ncreate type pulp_evr_t as (\n  epoch INT,\n  version pulp_evr_array_item[],\n  release pulp_evr_array_item[]\n);\n\nCREATE OR REPLACE FUNCTION pulp_evr_trigger() RETURNS trigger AS $$\n  BEGIN\n    NEW.evr = (select ROW(coalesce(NEW.epoch::numeric,0),\n                          pulp_rpmver_array(coalesce(NEW.version,'pulp_isempty'))::pulp_evr_array_item[],\n                          pulp_rpmver_array(coalesce(NEW.release,'pulp_isempty'))::pulp_evr_array_item[])::pulp_evr_t);\n    RETURN NEW;\n  END;\n$$ language 'plpgsql';\n\ncreate or replace FUNCTION pulp_isempty(t TEXT)\n  RETURNS BOOLEAN as $$\n  BEGIN\n    return t ~ '^[[:space:]]*$';\n  END;\n$$ language 'plpgsql';\n\ncreate or replace FUNCTION pulp_isalphanum(ch CHAR)\n  RETURNS BOOLEAN as $$\n  BEGIN\n    if ascii(ch) between ascii('a') and ascii('z') or\n      ascii(ch) between ascii('A') and ascii('Z') or\n      ascii(ch) between ascii('0') and ascii('9')\n    then\n      return TRUE;\n    end if;\n    return FALSE;\n  END;\n$$ language 'plpgsql';\n\ncreate or replace function pulp_isdigit(ch CHAR)\n  RETURNS BOOLEAN as $$\n  BEGIN\n    if ascii(ch) between ascii('0') and ascii('9')\n    then\n    return TRUE;\n    end if;\n    return FALSE;\n  END ;\n$$ language 'plpgsql';\n\ncreate or replace FUNCTION pulp_rpmver_array (string1 IN VARCHAR)\n  RETURNS pulp_evr_array_item[] as $$\n  declare\n    str1 VARCHAR := string1;\n    digits VARCHAR(10) := '0123456789';\n    lc_alpha VARCHAR(27) := 'abcdefghijklmnopqrstuvwxyz';\n    uc_alpha VARCHAR(27) := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';\n    alpha VARCHAR(54) := lc_alpha || uc_alpha;\n    one VARCHAR;\n    isnum BOOLEAN;\n    ver_array pulp_evr_array_item[] := ARRAY[]::pulp_evr_array_item[];\n  BEGIN\n    if str1 is NULL\n    then\n      RAISE EXCEPTION 'VALUE_ERROR.';\n    end if;\n\n    one := str1;\n    <<segment_loop>>\n    while one <> ''\n    loop\n      declare\n        segm1 VARCHAR;\n        segm1_n NUMERIC := 0;\n      begin\n        -- Throw out all non-alphanum characters\n        while one <> '' and not pulp_isalphanum(one)\n        loop\n          one := substr(one, 2);\n        end loop;\n        str1 := one;\n        if str1 <> '' and pulp_isdigit(str1)\n        then\n          str1 := ltrim(str1, digits);\n          isnum := true;\n        else\n          str1 := ltrim(str1, alpha);\n          isnum := false;\n        end if;\n        if str1 <> ''\n        then segm1 := substr(one, 1, length(one) - length(str1));\n        else segm1 := one;\n        end if;\n\n        if segm1 = '' then return ver_array; end if; /* arbitrary */\n        if isnum\n        then\n          segm1 := ltrim(segm1, '0');\n          if segm1 <> '' then segm1_n := segm1::numeric; end if;\n          segm1 := NULL;\n        else\n        end if;\n        ver_array := array_append(ver_array, (segm1_n, segm1)::pulp_evr_array_item);\n        one := str1;\n      end;\n    end loop segment_loop;\n\n    return ver_array;\n  END ;\n$$ language 'plpgsql';\n",
        ),
        migrations.RunSQL(
            sql='\n-- create pulp_evr_t on insert, so it matches the provided E/V/R cols\nCREATE TRIGGER pulp_evr_insert_trigger\n  BEFORE INSERT\n  ON rpm_package\n  FOR EACH ROW\n  EXECUTE PROCEDURE pulp_evr_trigger();\n\n-- create pulp_evr_t on update, so it continues to match the provided E/V/R cols, but only if Something Changed\nCREATE TRIGGER pulp_evr_update_trigger\n  BEFORE UPDATE OF epoch, version, release\n  ON rpm_package\n  FOR EACH ROW\n  WHEN (\n    OLD.epoch IS DISTINCT FROM NEW.epoch OR\n    OLD.version IS DISTINCT FROM NEW.version OR\n    OLD.release IS DISTINCT FROM NEW.release\n  )\n  EXECUTE PROCEDURE pulp_evr_trigger();\n',
        ),
        migrations.AddField(
            model_name='package',
            name='evr',
            field=pulp_rpm.app.models.package.RpmVersionField(null=True),
            preserve_default=False,
        ),
        migrations.RunSQL(
            sql='\nupdate rpm_package set evr = (\n  select ROW(coalesce(epoch::numeric,0),\n             pulp_rpmver_array(version)::pulp_evr_array_item[],\n             pulp_rpmver_array(release)::pulp_evr_array_item[])::pulp_evr_t\n  );\n',
        ),
        migrations.AlterField(
            model_name='package',
            name='evr',
            field=pulp_rpm.app.models.package.RpmVersionField(),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='retain_package_versions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repometadatafile',
            name='relative_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='repometadatafile',
            unique_together={('data_type', 'checksum', 'relative_path')},
        ),
        migrations.AlterField(
            model_name='variant',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.repository'),
        ),
        migrations.AddField(
            model_name='updatecollection',
            name='_update_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_collections', to='rpm.updaterecord'),
        ),
        migrations.RemoveField(
            model_name='updatecollection',
            name='update_record',
        ),
        migrations.RenameField(
            model_name='updatecollection',
            old_name='_update_record',
            new_name='update_record',
        ),
        migrations.AlterField(
            model_name='updatecollection',
            name='update_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='rpm.updaterecord'),
        ),
        migrations.AlterUniqueTogether(
            name='updatecollection',
            unique_together={('name', 'update_record')},
        ),
        migrations.AlterField(
            model_name='distributiontree',
            name='base_product_short',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='distributiontree',
            name='release_short',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variant',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='core.repository'),
        ),
        migrations.AddField(
            model_name='rpmpublication',
            name='gpgcheck',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='rpmpublication',
            name='repo_gpgcheck',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='checksum',
            name='checksum',
            field=models.CharField(max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='last_sync_repomd_checksum',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='rpmpublication',
            name='sqlite_metadata',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='updaterecord',
            name='updated_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='modulemd',
            name='static_context',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='UlnRemote',
            fields=[
                ('remote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_ulnremote', serialize=False, to='core.remote')),
                ('uln_server_base_url', models.CharField(max_length=512, null=True)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.remote',),
        ),
        migrations.CreateModel(
            name='NewRpmDistribution',
            fields=[
                ('distribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_rpmdistribution', serialize=False, to='core.distribution')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.distribution',),
        ),
        migrations.RunPython(
            code=pulp_rpm.app.migrations.0033_new_distribution_model.migrate_data_from_old_model_to_new_model_up,
            reverse_code=pulp_rpm.app.migrations.0033_new_distribution_model.migrate_data_from_old_model_to_new_model_down,
        ),
        migrations.DeleteModel(
            name='RpmDistribution',
        ),
        migrations.RenameModel(
            old_name='NewRpmDistribution',
            new_name='RpmDistribution',
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='autopublish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='gpgcheck',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='metadata_checksum_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], default='sha256', max_length=10),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='package_checksum_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], default='sha256', max_length=10),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='repo_gpgcheck',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='sqlite_metadata',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rpmrepository',
            name='metadata_checksum_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rpmrepository',
            name='package_checksum_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='rpmrepository',
            name='sub_repo',
        ),
        migrations.AlterField(
            model_name='modulemd',
            name='artifacts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='modulemd',
            name='dependencies',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='modulemddefaults',
            name='profiles',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='changelogs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='conflicts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='enhances',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='files',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='obsoletes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='provides',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='recommends',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='requires',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='suggests',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='supplements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='desc_by_lang',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='group_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='name_by_lang',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='packageenvironment',
            name='desc_by_lang',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='packageenvironment',
            name='group_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='packageenvironment',
            name='name_by_lang',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='packageenvironment',
            name='option_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='packagegroup',
            name='desc_by_lang',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='packagegroup',
            name='name_by_lang',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='packagegroup',
            name='packages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='packagelangpacks',
            name='matches',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rpmrepository',
            name='original_checksum_types',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='updatecollection',
            name='module',
            field=models.JSONField(null=True),
        ),
        migrations.RemoveField(
            model_name='rpmrepository',
            name='last_sync_remote',
        ),
        migrations.RemoveField(
            model_name='rpmrepository',
            name='last_sync_repo_version',
        ),
        migrations.RemoveField(
            model_name='rpmrepository',
            name='last_sync_repomd_checksum',
        ),
        migrations.RemoveField(
            model_name='rpmrepository',
            name='last_sync_revision_number',
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='last_sync_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='distributiontree',
            name='digest',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='distributiontree',
            unique_together={('digest',)},
        ),
        migrations.CreateModel(
            name='RpmAlternateContentSource',
            fields=[
                ('alternatecontentsource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_rpmalternatecontentsource', serialize=False, to='core.alternatecontentsource')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.alternatecontentsource',),
        ),
        migrations.CreateModel(
            name='ModulemdObsolete',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_modulemdobsolete', serialize=False, to='core.content')),
                ('modified', models.DateTimeField()),
                ('module_name', models.TextField()),
                ('module_stream', models.TextField()),
                ('message', models.TextField()),
                ('override_previous', models.BooleanField(null=True)),
                ('module_context', models.TextField(null=True)),
                ('eol_date', models.DateTimeField(null=True)),
                ('obsoleted_by_module_name', models.TextField(null=True)),
                ('obsoleted_by_module_stream', models.TextField(null=True)),
                ('snippet', models.TextField()),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('modified', 'module_name', 'module_stream')},
            },
            bases=('core.content',),
        ),
        migrations.AlterField(
            model_name='repometadatafile',
            name='data_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='addon',
            name='addon_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='addon',
            name='packages',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='addon',
            name='type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='addon',
            name='uid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checksum',
            name='checksum',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checksum',
            name='path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='distributiontree',
            name='arch',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='distributiontree',
            name='base_product_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='distributiontree',
            name='base_product_short',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='distributiontree',
            name='base_product_version',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='distributiontree',
            name='digest',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='distributiontree',
            name='header_version',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='distributiontree',
            name='instimage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='distributiontree',
            name='mainimage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='distributiontree',
            name='release_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='distributiontree',
            name='release_short',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='distributiontree',
            name='release_version',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='platforms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modulemd',
            name='arch',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modulemd',
            name='context',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modulemd',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modulemd',
            name='stream',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modulemd',
            name='version',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modulemddefaults',
            name='digest',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='modulemddefaults',
            name='module',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modulemddefaults',
            name='stream',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='checksum_type',
            field=models.TextField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')]),
        ),
        migrations.AlterField(
            model_name='package',
            name='pkgId',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='digest',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='packageenvironment',
            name='digest',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='packageenvironment',
            name='id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='packageenvironment',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='packagegroup',
            name='digest',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='packagegroup',
            name='id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='packagegroup',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='packagelangpacks',
            name='digest',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='repometadatafile',
            name='checksum',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='repometadatafile',
            name='checksum_type',
            field=models.TextField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')]),
        ),
        migrations.AlterField(
            model_name='rpmpublication',
            name='metadata_checksum_type',
            field=models.TextField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')]),
        ),
        migrations.AlterField(
            model_name='rpmpublication',
            name='package_checksum_type',
            field=models.TextField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')]),
        ),
        migrations.AlterField(
            model_name='rpmremote',
            name='sles_auth_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rpmrepository',
            name='metadata_checksum_type',
            field=models.TextField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], null=True),
        ),
        migrations.AlterField(
            model_name='rpmrepository',
            name='package_checksum_type',
            field=models.TextField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], null=True),
        ),
        migrations.AlterField(
            model_name='ulnremote',
            name='uln_server_base_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='updaterecord',
            name='digest',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='updaterecord',
            name='id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='debug_packages',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='debug_repository',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='identity',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variant',
            name='packages',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variant',
            name='source_packages',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='source_repository',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variant',
            name='uid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant_id',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='modulemd',
            name='snippet',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulemddefaults',
            name='snippet',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulemd',
            name='description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulemd',
            name='profiles',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterModelOptions(
            name='rpmalternatecontentsource',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('refresh_rpmalternatecontentsource', 'Refresh an Alternate Content Source'), ('manage_roles_rpmalternatecontentsource', 'Can manage roles on ACS')]},
        ),
        migrations.AlterModelOptions(
            name='rpmdistribution',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('manage_roles_rpmdistribution', 'Can manage roles on an RPM distribution')]},
        ),
        migrations.AlterModelOptions(
            name='rpmpublication',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('manage_roles_rpmpublication', 'Can manage roles on an RPM publication')]},
        ),
        migrations.AlterModelOptions(
            name='rpmremote',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('manage_roles_rpmremote', 'Can manage roles on an RPM remotes')]},
        ),
        migrations.AlterModelOptions(
            name='rpmrepository',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('manage_roles_rpmrepository', 'Can manage roles on RPM repositories'), ('modify_content_rpmrepository', 'Add content to, or remove content from a repository'), ('repair_rpmrepository', 'Copy a repository'), ('sync_rpmrepository', 'Sync a repository'), ('delete_rpmrepository_version', 'Delete a repository version')]},
        ),
        migrations.AlterModelOptions(
            name='ulnremote',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('manage_roles_ulnremote', 'Can manage roles on an ULN remotes')]},
        ),
        migrations.AlterField(
            model_name='modulemdobsolete',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='modulemdobsolete',
            name='eol_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='modulemdobsolete',
            name='eol_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='modulemdobsolete',
            name='modified',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checksum',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributiontree',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content'),
        ),
        migrations.AlterField(
            model_name='image',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modulemd',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content'),
        ),
        migrations.AlterField(
            model_name='modulemd',
            name='packages',
            field=models.ManyToManyField(to='rpm.package'),
        ),
        migrations.AlterField(
            model_name='modulemddefaults',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content'),
        ),
        migrations.AlterField(
            model_name='modulemdobsolete',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content'),
        ),
        migrations.AlterField(
            model_name='package',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content'),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content'),
        ),
        migrations.AlterField(
            model_name='packageenvironment',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content'),
        ),
        migrations.AlterField(
            model_name='packagegroup',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content'),
        ),
        migrations.AlterField(
            model_name='packagelangpacks',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content'),
        ),
        migrations.AlterField(
            model_name='repometadatafile',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content'),
        ),
        migrations.AlterField(
            model_name='rpmalternatecontentsource',
            name='alternatecontentsource_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.alternatecontentsource'),
        ),
        migrations.AlterField(
            model_name='rpmdistribution',
            name='distribution_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.distribution'),
        ),
        migrations.AlterField(
            model_name='rpmpublication',
            name='publication_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.publication'),
        ),
        migrations.AlterField(
            model_name='rpmremote',
            name='remote_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.remote'),
        ),
        migrations.AlterField(
            model_name='rpmrepository',
            name='metadata_signing_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.asciiarmoreddetachedsigningservice'),
        ),
        migrations.AlterField(
            model_name='rpmrepository',
            name='repository_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.repository'),
        ),
        migrations.AlterField(
            model_name='ulnremote',
            name='remote_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.remote'),
        ),
        migrations.AlterField(
            model_name='updatecollection',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='updatecollectionpackage',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='updaterecord',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content'),
        ),
        migrations.AlterField(
            model_name='updatereference',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variant',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='distributiontree',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='modulemd',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='modulemdobsolete',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='repometadatafile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='distributiontree',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='modulemd',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='modulemddefaults',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='modulemdobsolete',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='package',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='packageenvironment',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='packagegroup',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='packagelangpacks',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='repometadatafile',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='updaterecord',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AlterField(
            model_name='modulemddefaults',
            name='digest',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='pkgId',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='digest',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='packageenvironment',
            name='digest',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='packagegroup',
            name='digest',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='packagelangpacks',
            name='digest',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='updaterecord',
            name='digest',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='distributiontree',
            unique_together={('_pulp_domain', 'digest')},
        ),
        migrations.AlterUniqueTogether(
            name='modulemd',
            unique_together={('_pulp_domain', 'name', 'stream', 'version', 'context', 'arch')},
        ),
        migrations.AlterUniqueTogether(
            name='modulemddefaults',
            unique_together={('_pulp_domain', 'digest')},
        ),
        migrations.AlterUniqueTogether(
            name='modulemdobsolete',
            unique_together={('_pulp_domain', 'modified', 'module_name', 'module_stream')},
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('_pulp_domain', 'name', 'epoch', 'version', 'release', 'arch', 'checksum_type', 'pkgId')},
        ),
        migrations.AlterUniqueTogether(
            name='packagecategory',
            unique_together={('_pulp_domain', 'digest')},
        ),
        migrations.AlterUniqueTogether(
            name='packageenvironment',
            unique_together={('_pulp_domain', 'digest')},
        ),
        migrations.AlterUniqueTogether(
            name='packagegroup',
            unique_together={('_pulp_domain', 'digest')},
        ),
        migrations.AlterUniqueTogether(
            name='packagelangpacks',
            unique_together={('_pulp_domain', 'digest')},
        ),
        migrations.AlterUniqueTogether(
            name='repometadatafile',
            unique_together={('_pulp_domain', 'data_type', 'checksum', 'relative_path')},
        ),
        migrations.AlterUniqueTogether(
            name='updaterecord',
            unique_together={('_pulp_domain', 'digest')},
        ),
        migrations.AlterField(
            model_name='addon',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='modulemd',
            name='digest',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='modulemd',
            unique_together={('_pulp_domain', 'name', 'stream', 'version', 'context', 'arch', 'digest')},
        ),
        migrations.AddField(
            model_name='rpmdistribution',
            name='generate_repo_config',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='rpmpublication',
            name='gpgcheck',
        ),
        migrations.RemoveField(
            model_name='rpmpublication',
            name='repo_gpgcheck',
        ),
        migrations.RemoveField(
            model_name='rpmrepository',
            name='gpgcheck',
        ),
        migrations.RemoveField(
            model_name='rpmrepository',
            name='repo_gpgcheck',
        ),
        migrations.AddField(
            model_name='rpmpublication',
            name='repo_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='repo_config',
            field=models.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name='rpmpublication',
            name='sqlite_metadata',
        ),
        migrations.RemoveField(
            model_name='rpmrepository',
            name='sqlite_metadata',
        ),
        migrations.AddField(
            model_name='rpmpublication',
            name='checksum_type',
            field=models.TextField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], null=True),
        ),
        migrations.AlterField(
            model_name='rpmpublication',
            name='checksum_type',
            field=models.TextField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')]),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='checksum_type',
            field=models.TextField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], null=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='addons', to='core.repository'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='variants', to='core.repository'),
        ),
        migrations.AddField(
            model_name='rpmpublication',
            name='compression_type',
            field=models.TextField(choices=[('zstd', 'zstd'), ('gz', 'gz')], null=True),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='compression_type',
            field=models.TextField(choices=[('zstd', 'zstd'), ('gz', 'gz')], null=True),
        ),
        migrations.CreateModel(
            name='RpmPackageSigningService',
            fields=[
                ('signingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.signingservice')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.signingservice',),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='package_signing_fingerprint',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rpmrepository',
            name='package_signing_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpm.rpmpackagesigningservice'),
        ),
    ]
