# Generated by Django 2.2.4 on 2019-08-30 20:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_duplicated_reserved_resources'),
        ('rpm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionTree',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_distributiontree', serialize=False, to='core.Content')),
                ('header_version', models.CharField(max_length=10)),
                ('release_name', models.CharField(max_length=50)),
                ('release_short', models.CharField(max_length=20)),
                ('release_version', models.CharField(max_length=10)),
                ('release_is_layered', models.BooleanField(default=False)),
                ('base_product_name', models.CharField(max_length=50, null=True)),
                ('base_product_short', models.CharField(max_length=20, null=True)),
                ('base_product_version', models.CharField(max_length=10, null=True)),
                ('arch', models.CharField(max_length=30)),
                ('build_timestamp', models.FloatField()),
                ('instimage', models.CharField(max_length=50, null=True)),
                ('mainimage', models.CharField(max_length=50, null=True)),
                ('discnum', models.IntegerField(null=True)),
                ('totaldiscs', models.IntegerField(null=True)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('header_version', 'release_name', 'release_short', 'release_version', 'arch', 'build_timestamp')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('variant_id', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('packages', models.CharField(max_length=50)),
                ('source_packages', models.CharField(max_length=50, null=True)),
                ('source_repository', models.CharField(max_length=50, null=True)),
                ('debug_packages', models.CharField(max_length=50, null=True)),
                ('debug_repository', models.CharField(max_length=50, null=True)),
                ('identity', models.CharField(max_length=50, null=True)),
                ('distribution_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='rpm.DistributionTree')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Repository')),
            ],
            options={
                'unique_together': {('variant_id', 'uid', 'name', 'type', 'packages', 'distribution_tree')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=128)),
                ('platforms', models.CharField(max_length=20)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Artifact')),
                ('distribution_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rpm.DistributionTree')),
            ],
            options={
                'unique_together': {('name', 'path', 'platforms', 'distribution_tree')},
            },
        ),
        migrations.CreateModel(
            name='Checksum',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('path', models.CharField(max_length=128)),
                ('checksum', models.CharField(max_length=128, null=True)),
                ('distribution_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checksums', to='rpm.DistributionTree')),
            ],
            options={
                'unique_together': {('path', 'checksum', 'distribution_tree')},
            },
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('addon_id', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('packages', models.CharField(max_length=50)),
                ('distribution_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='rpm.DistributionTree')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addons', to='core.Repository')),
            ],
            options={
                'unique_together': {('addon_id', 'uid', 'name', 'type', 'packages', 'distribution_tree')},
            },
        ),
    ]
