# Generated by Django 2.2.5 on 2019-09-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_duplicated_reserved_resources'),
        ('rpm', '0002_kickstarts'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoMetadataFile',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_repometadatafile', serialize=False, to='core.Content')),
                ('data_type', models.CharField(max_length=20)),
                ('checksum_type', models.CharField(max_length=6)),
                ('checksum', models.CharField(max_length=128)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('data_type', 'checksum')},
            },
            bases=('core.content',),
        ),
    ]
