# Generated by Django 2.2.10 on 2020-02-19 14:43

import json

from django.db import migrations, transaction


def unflatten_json(apps, schema_editor):
    # re: https://pulp.plan.io/issues/6191
    with transaction.atomic():
        Modulemd = apps.get_model('rpm', 'Modulemd')
        for module in Modulemd.objects.all().only('artifacts', 'dependencies'):
            module.artifacts = json.loads(module.artifacts)
            module.dependencies = json.loads(module.dependencies)
            module.save()

        ModulemdDefaults = apps.get_model('rpm', 'ModulemdDefaults')
        for mod_defs in ModulemdDefaults.objects.all().only('profiles'):
            mod_defs.profiles = json.loads(mod_defs.profiles)
            mod_defs.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0002_updaterecord_reboot_suggested'),
    ]

    operations = [
        migrations.RunPython(unflatten_json),
    ]
