# Generated by Django 2.2.6 on 2019-10-03 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0004_jsonfields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='_created',
            new_name='pulp_created',
        ),
        migrations.RenameField(
            model_name='addon',
            old_name='_id',
            new_name='pulp_id',
        ),
        migrations.RenameField(
            model_name='addon',
            old_name='_last_updated',
            new_name='pulp_last_updated',
        ),
        migrations.RenameField(
            model_name='checksum',
            old_name='_created',
            new_name='pulp_created',
        ),
        migrations.RenameField(
            model_name='checksum',
            old_name='_id',
            new_name='pulp_id',
        ),
        migrations.RenameField(
            model_name='checksum',
            old_name='_last_updated',
            new_name='pulp_last_updated',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='_created',
            new_name='pulp_created',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='_id',
            new_name='pulp_id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='_last_updated',
            new_name='pulp_last_updated',
        ),
        migrations.RenameField(
            model_name='updatecollection',
            old_name='_created',
            new_name='pulp_created',
        ),
        migrations.RenameField(
            model_name='updatecollection',
            old_name='_id',
            new_name='pulp_id',
        ),
        migrations.RenameField(
            model_name='updatecollection',
            old_name='_last_updated',
            new_name='pulp_last_updated',
        ),
        migrations.RenameField(
            model_name='updatecollectionpackage',
            old_name='_created',
            new_name='pulp_created',
        ),
        migrations.RenameField(
            model_name='updatecollectionpackage',
            old_name='_id',
            new_name='pulp_id',
        ),
        migrations.RenameField(
            model_name='updatecollectionpackage',
            old_name='_last_updated',
            new_name='pulp_last_updated',
        ),
        migrations.RenameField(
            model_name='updatereference',
            old_name='_created',
            new_name='pulp_created',
        ),
        migrations.RenameField(
            model_name='updatereference',
            old_name='_id',
            new_name='pulp_id',
        ),
        migrations.RenameField(
            model_name='updatereference',
            old_name='_last_updated',
            new_name='pulp_last_updated',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='_created',
            new_name='pulp_created',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='_id',
            new_name='pulp_id',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='_last_updated',
            new_name='pulp_last_updated',
        ),
        migrations.AlterField(
            model_name='updatecollectionpackage',
            name='update_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='rpm.UpdateCollection', to_field='pulp_id'),
        ),
    ]
