# Generated by Django 2.2.6 on 2019-10-25 18:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_relative_path'),
        ('rpm', '0005_pulp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_packagecategory', serialize=False, to='core.Content')),
                ('id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('display_order', models.IntegerField()),
                ('group_ids', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('desc_by_lang', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name_by_lang', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('digest', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='PackageEnvironment',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_packageenvironment', serialize=False, to='core.Content')),
                ('id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('display_order', models.IntegerField(null=True)),
                ('group_ids', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('option_ids', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('desc_by_lang', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name_by_lang', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('digest', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='PackageLangpacks',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rpm_packagelangpacks', serialize=False, to='core.Content')),
                ('matches', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('digest', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.content',),
        ),
        migrations.RemoveField(
            model_name='environment',
            name='content_ptr',
        ),
        migrations.RemoveField(
            model_name='langpacks',
            name='content_ptr',
        ),
        migrations.AddField(
            model_name='packagegroup',
            name='related_packages',
            field=models.ManyToManyField(related_name='rpm_packagegroup', to='rpm.Package'),
        ),
        migrations.AlterField(
            model_name='packagegroup',
            name='desc_by_lang',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='packagegroup',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='packagegroup',
            name='name_by_lang',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='packagegroup',
            name='packages',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
        migrations.DeleteModel(
            name='Langpacks',
        ),
        migrations.AddField(
            model_name='packageenvironment',
            name='optionalgroups',
            field=models.ManyToManyField(related_name='optionalgroups_to_env', to='rpm.PackageGroup'),
        ),
        migrations.AddField(
            model_name='packageenvironment',
            name='packagegroups',
            field=models.ManyToManyField(related_name='packagegroups_to_env', to='rpm.PackageGroup'),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='packagegroups',
            field=models.ManyToManyField(related_name='rpm_packagecategory', to='rpm.PackageGroup'),
        ),
    ]
