# Generated by Django 2.2.6 on 2019-11-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0006_auto_20191025_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagecategory',
            name='display_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='packagegroup',
            name='display_order',
            field=models.IntegerField(null=True),
        ),
    ]
