# Generated by Django 2.2.7 on 2019-11-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0008_rpmrepository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatereference',
            name='ref_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='updatereference',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
