# Generated by Django 2.2.7 on 2019-11-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0009_auto_20191111_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpmrepository',
            name='sub_repo',
            field=models.BooleanField(default=False),
        ),
    ]
