# Generated by Django 2.2.19 on 2021-03-19 17:42

from django.db import connection, migrations, models, transaction
import django.db.models.deletion


pks_to_delete = []


def migrate_data_from_old_master_model_to_new_master_model(apps, schema_editor):
    RpmDistribution = apps.get_model('rpm', 'RpmDistribution')
    CoreDistribution = apps.get_model('core', 'Distribution')
    for old_file_distribution in RpmDistribution.objects.all():
        with transaction.atomic():
            new_master_model_entry = CoreDistribution(
                pulp_id=old_file_distribution.pulp_id,
                pulp_created=old_file_distribution.pulp_created,
                pulp_last_updated=old_file_distribution.pulp_last_updated,
                pulp_type=old_file_distribution.pulp_type,
                name=old_file_distribution.name,
                base_path=old_file_distribution.base_path,
                content_guard=old_file_distribution.content_guard,
                remote=old_file_distribution.remote,
                publication=old_file_distribution.publication,
            )
            new_master_model_entry.save()
            old_file_distribution.distribution_ptr = new_master_model_entry
            old_file_distribution.save()
            pks_to_delete.append(old_file_distribution.pulp_id)


def delete_remaining_old_master_model_entries(apps, schema_editor):
    with connection.cursor() as cursor:
        for pk in pks_to_delete:
            cursor.execute("DELETE from core_basedistribution WHERE pulp_id = %s", [pk])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_add_new_distribution_mastermodel'),
        ('rpm', '0031_ulnremote'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpmdistribution',
            name='distribution_ptr',
            field=models.OneToOneField(auto_created=True, null=True, default=None,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       parent_link=True, primary_key=False,
                                       related_name='rpm_rpmdistribution', serialize=False,
                                       to='core.Distribution'),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_data_from_old_master_model_to_new_master_model),
        migrations.RemoveField(
            model_name='rpmdistribution',
            name='basedistribution_ptr',
        ),
        migrations.AlterField(
            model_name='rpmdistribution',
            name='distribution_ptr',
            field=models.OneToOneField(auto_created=True,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       parent_link=True, primary_key=True,
                                       related_name='rpm_rpmdistribution', serialize=False,
                                       to='core.Distribution'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rpmdistribution',
            name='publication',
        ),
        migrations.RunPython(delete_remaining_old_master_model_entries),
    ]
