# Generated by Django 2.2.24 on 2021-06-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0035_fix_auto_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpmrepository',
            name='metadata_checksum_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rpmrepository',
            name='package_checksum_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], max_length=10, null=True),
        ),
    ]
