# Generated by Django 3.2.6 on 2021-08-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0037_DATA_remove_rpmrepository_sub_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpmrepository',
            name='metadata_checksum_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='rpmrepository',
            name='package_checksum_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('md5', 'md5'), ('sha1', 'sha1'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], default='unknown', max_length=10),
        ),
    ]
