# Generated by Django 3.2.9 on 2021-12-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0038_fix_sync_optimization'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributiontree',
            name='digest',
            field=models.CharField(default='should be removed from a repo version with a sync', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='distributiontree',
            unique_together={('digest',)},
        ),
    ]
