# Generated by Django 3.2.13 on 2022-06-15 22:18

import os

from django.db import migrations, models


def strip_relative_prefix(apps, schema_editor):
    RpmPackage = apps.get_model("rpm", "Package")
    pkgs = []
    for package in RpmPackage.objects.all().iterator():
        package.filename = os.path.basename(package.location_href)
        pkgs.append(package)
        if len(pkgs) > 1000:
            RpmPackage.objects.bulk_update(pkgs, ["filename"])
            pkgs.clear()


def fake_relative_prefix(apps, schema_editor):
    RpmPackage = apps.get_model("rpm", "Package")
    pkgs = []
    for package in RpmPackage.objects.all().iterator():
        package.location_href = "Packages/" + package.filename
        pkgs.append(package)
        if len(pkgs) > 1000:
            RpmPackage.objects.bulk_update(pkgs, ["filename"])
            pkgs.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0043_textfield_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='filename',
            field=models.TextField(),
        ),
        migrations.RunPython(
            strip_relative_prefix,
            reverse_code=fake_relative_prefix
        ),
        migrations.RemoveField(
            model_name='package',
            name='location_base',
        ),
        migrations.RemoveField(
            model_name='package',
            name='location_href',
        ),
    ]
