# Generated by Django 3.2.15 on 2022-08-29 16:33

from django.db import migrations, models, transaction

import ast
import gi
import logging

gi.require_version("Modulemd", "2.0")
from gi.repository import Modulemd as mmdlib  # noqa: E402


logger = logging.getLogger(__name__)


def populate_new_fields(apps, schema_editor):
    """Populate new fields of modulemd."""
    Modulemd = apps.get_model("rpm", "Modulemd")
    ModulemdDefaults = apps.get_model("rpm", "ModulemdDefaults")
    modules_to_update = []

    # Fix issue #2786 if already tried to update to 3.18.1
    modulemds_to_update = []
    for modulemd in Modulemd.objects.filter(snippet__startswith="b\'---"):
        modulemd.snippet = ast.literal_eval(modulemd.snippet).decode("utf8")
        modulemds_to_update.append(modulemd)
    Modulemd.objects.bulk_update(modulemds_to_update, ["snippet"])

    # Same issue (#2786) has happened to modulemd defaults
    modulemd_defaults_to_update = []
    for default in ModulemdDefaults.objects.filter(snippet__startswith="b\'---"):
        default.snippet = ast.literal_eval(default.snippet).decode("utf8")
        modulemd_defaults_to_update.append(default)
    ModulemdDefaults.objects.bulk_update(modulemd_defaults_to_update, ["snippet"])

    for modulemd in Modulemd.objects.filter(profiles={}):
        module_index = mmdlib.ModuleIndex.new()
        try:
            ret, err = module_index.update_from_string(modulemd.snippet, False)
            if err:
                raise ValueError(
                    "Repair failed on module "
                    f"'{modulemd.name}.{modulemd.stream}.{modulemd.version}'."
                )
            for module in module_index.get_module_names():
                for stream in module_index.get_module(module).get_all_streams():
                    modulemd.profiles = {}
                    modulemd.description = stream.get_description()
                    for profile in stream.get_profile_names():
                        stream_profile = stream.get_profile(profile)
                        modulemd.profiles[profile] = stream_profile.get_rpms()
                        modules_to_update.append(modulemd)
        except ValueError as err:
            # Due to issue #2735 it could happen that snippet will be empty
            # https://github.com/pulp/pulp_rpm/issues/2735
            logger.warning(
                "Modulemd {}-{}-{} cannot populate new fields."
                "So it will miss the info about profiles and its description.".format(
                    modulemd.name, modulemd.stream, modulemd.version
                )
            )

    Modulemd.objects.bulk_update(modules_to_update, ["profiles", "description"])


class Migration(migrations.Migration):

    dependencies = [
        ("rpm", "0044_noartifact_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulemd",
            name="description",
            field=models.TextField(default="Description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="modulemd",
            name="profiles",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(populate_new_fields),
    ]
