# Generated by Django 3.2.15 on 2022-09-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rpm", "0045_noartifact_modules"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="updatecollectionpackage",
            unique_together={("name", "epoch", "version", "release", "arch", "update_collection")},
        ),
    ]
