# Generated by Django 3.2.16 on 2022-12-08 17:46

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.util


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_add_domain_relations'),
        ('rpm', '0046_rbac_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributiontree',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, related_name='rpm_distributiontree', to='core.domain'),
        ),
        migrations.AddField(
            model_name='modulemd',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, related_name='rpm_modulemd', to='core.domain'),
        ),
        migrations.AddField(
            model_name='modulemddefaults',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, related_name='rpm_modulemddefaults', to='core.domain'),
        ),
        migrations.AddField(
            model_name='modulemdobsolete',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, related_name='rpm_modulemdobsolete', to='core.domain'),
        ),
        migrations.AddField(
            model_name='package',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, related_name='rpm_package', to='core.domain'),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, related_name='rpm_packagecategory', to='core.domain'),
        ),
        migrations.AddField(
            model_name='packageenvironment',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, related_name='rpm_packageenvironment', to='core.domain'),
        ),
        migrations.AddField(
            model_name='packagegroup',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, related_name='rpm_packagegroup', to='core.domain'),
        ),
        migrations.AddField(
            model_name='packagelangpacks',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, related_name='rpm_packagelangpacks', to='core.domain'),
        ),
        migrations.AddField(
            model_name='repometadatafile',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, related_name='rpm_repometadatafile', to='core.domain'),
        ),
        migrations.AddField(
            model_name='updaterecord',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, related_name='rpm_updaterecord', to='core.domain'),
        ),
        migrations.AlterUniqueTogether(
            name='distributiontree',
            unique_together={('digest', 'pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='modulemd',
            unique_together={('name', 'stream', 'version', 'context', 'arch', 'pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='modulemddefaults',
            unique_together={('digest', 'pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='modulemdobsolete',
            unique_together={('modified', 'module_name', 'module_stream', 'pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('name', 'epoch', 'version', 'release', 'arch', 'checksum_type', 'pkgId', 'pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='packagecategory',
            unique_together={('digest', 'pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='packageenvironment',
            unique_together={('digest', 'pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='packagegroup',
            unique_together={('digest', 'pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='packagelangpacks',
            unique_together={('digest', 'pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='repometadatafile',
            unique_together={('data_type', 'checksum', 'relative_path', 'pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='updaterecord',
            unique_together={('id', 'pulp_domain')},
        ),
    ]
