# Generated by Django 3.2.17 on 2023-02-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpm", "0047_modulemd_datefield"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="signer_key_id",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="rpmrepository",
            name="allowed_pub_keys",
            field=models.JSONField(default=list),
        ),
    ]
