# Generated by Django 4.2.4 on 2023-09-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpm", "0053_rpmdistribution_generate_repo_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rpmpublication",
            name="gpgcheck",
        ),
        migrations.RemoveField(
            model_name="rpmpublication",
            name="repo_gpgcheck",
        ),
        migrations.RemoveField(
            model_name="rpmrepository",
            name="gpgcheck",
        ),
        migrations.RemoveField(
            model_name="rpmrepository",
            name="repo_gpgcheck",
        ),
    ]
