# Generated by Django 4.2.7 on 2024-02-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0116_alter_remoteartifact_md5_alter_remoteartifact_sha1_and_more"),
        ("rpm", "0059_rpmpublication_compression_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RpmPackageSigningService",
            fields=[
                (
                    "signingservice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.signingservice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.signingservice",),
        ),
    ]
