# Generated by Django 4.2.7 on 2024-02-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0060_rpmpackagesigningservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpmrepository',
            name='package_signing_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpm.rpmpackagesigningservice'),
        ),
    ]
