# Generated by Django 4.2.27 on 2026-02-25 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0068_alter_rpmpublication_compression_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pulp_signing_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=None, null=True, size=None),
        ),
    ]
