# Generated by Django 5.2.11 on 2026-03-05 22:40

from django.db import migrations, models


def remove_nested_by_both_layout_as_publication_option(apps, schema_editor):
    RpmRepository = apps.get_model("rpm", "RpmRepository")
    RpmPublication = apps.get_model("rpm", "RpmPublication")
    RpmRepository.objects.filter(layout="nested_by_both").update(
        layout="nested_by_digest"
    )
    RpmPublication.objects.filter(layout="nested_by_both").update(
        layout="nested_by_digest"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0070_add_rpm_signing_keys'),
    ]

    operations = [
        migrations.RunPython(
            remove_nested_by_both_layout_as_publication_option,
        ),
        migrations.AlterField(
            model_name='rpmpublication',
            name='layout',
            field=models.TextField(choices=[('nested_alphabetically', 'nested_alphabetically'), ('flat', 'flat'), ('nested_by_digest', 'nested_by_digest')], null=True),
        ),
        migrations.AlterField(
            model_name='rpmrepository',
            name='layout',
            field=models.TextField(choices=[('nested_alphabetically', 'nested_alphabetically'), ('flat', 'flat'), ('nested_by_digest', 'nested_by_digest')], null=True),
        ),
    ]
