# Generated by Django 5.2.17 on 2026-08-18 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0073_evr_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpmrepository',
            name='metadata_signing_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.asciiarmoreddetachedsigningservice'),
        ),
        migrations.AlterField(
            model_name='rpmrepository',
            name='package_signing_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rpm.rpmpackagesigningservice'),
        ),
    ]
