# Generated by Django 5.2.16 on 2026-08-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0073_evr_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagegroup',
            name='langonly',
            field=models.TextField(null=True),
        ),
    ]
